### ISSUE TITLE
Correct price in Log

### ISSUE THREAD

**Issue by mpi42** [aviddot/Pancakeswap-v2-trading-bot#10]
Hi 

in the log i only see 6 dec. on the price
![image](https://user-images.githubusercontent.com/50237136/116728953-da998b00-a9e6-11eb-842d-4b2175f50c84.png)

for example moontoken 0x81e4d494b85a24a58a6ba45c9b418b32a4e039de but not the full actual price
and für yoshi token: 0x701317a21e545d79331f3e2d26cc2f2fa853f9ad there is a price with 0.072377 but should be around $0.000000000072377

is this only a display error or can i do something here?

thank you in advance

**Comment by aviddot** [comment]
You have to set the amount of decimals the token has in the 'Dec' column, yoshi has 9 decimals and not the standard 18, that is why the price is showing wrong.

The price display is set at 6 decimals max, if the value is less than that the price is not shown, I might increase it to 8 decimals soon as there are so much shit tokens around these days.

**Comment by aviddot** [comment]
Done!
