### ISSUE TITLE
Division by 0 in lin 343

### ISSUE THREAD

**Issue by PlesaMihai** [aviddot/Pancakeswap-v2-trading-bot#2]
Get this error whent trying to strat the bot with a token on bsc, trading with BNB
Token: 0x3da67ae8fcf0b733d799f65b2695d650ea11112a
Buy: 0.000105
Sell: 0.00018
![image](https://user-images.githubusercontent.com/57940109/116388375-7202b080-a824-11eb-9c82-b9e2553f27a9.png)

**Comment by aviddot** [comment]
The token you use there has 9 decimals. Please change the 18 to 9 in the column 'Dec.'.

**Comment by PlesaMihai** [comment]
Done it but now i get division by zero on line: 340

**Comment by aviddot** [comment]
Was a simple fix, the bot was not made to work with tokens that have such a low value. Commit: https://github.com/aviddot/Pancakeswap-v2-trading-bot/commit/c39510c5ac38ff5a7cd349e339adff1b21e44e1c

I will update the .exe file somewhere today.
