### ISSUE TITLE
wich wallet and any futher information

### ISSUE THREAD

**Issue by mpi42** [aviddot/Pancakeswap-v2-trading-bot#3]
hi wich wallet are you using or wich one works best with it? because on metamask you need to accept every transaktion

**Comment by aviddot** [comment]
I'm not sure what you mean. Metamask is the wallet I use, but it has nothing to do with whether or not it works with  the bot. All wallets have an address and a private key. The only wallet you cant use with the bot, is a wallet that is stored on a ledger or trezor, if this is what you mean, you'll have to make a new wallet (with metamask).

To get private key in metamask, follow this guide: https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-Export-an-Account-Private-Key

Please never share this key with anyone and try to understand why that is important.

**Comment by aviddot** [comment]
I'll close this as it does not really have to do with the bot
