### ISSUE TITLE
How to use it for BEP network?

### ISSUE THREAD

**Issue by lschaupp** [aviddot/Pancakeswap-v2-trading-bot#5]
Did you find any flag parameter?
But in the readme it says that it would exist.
Could you show me where?

**Comment by aviddot** [comment]
That is meant for something else, to let tokens trade with each other. Ill have to edit the name

**Comment by lschaupp** [comment]
So the tool will not work on the Binance Smart Chain (BEP20)? Right?
And if not, how much work would it be to add the functionality?

**Comment by aviddot** [comment]
No, it should be BEP20, works with bsc. I'll update the name in the next update. Trading with BEP20 means that tokens trade also with each other, instead of only with the main coin/token option.

Please read the section 'Tokentokennumerator' in the repo homepage to see how this works.
