### ISSUE TITLE
Sell order is not being executed

### ISSUE THREAD

**Issue by LovetheWayIPlay** [aviddot/Pancakeswap-v2-trading-bot#8]
Hi Aviddot, 

i recently tried your bot and its working fine with the buy orders. Unfortunately the sell order is not getting executed when the price reaches the the value i typed in. 

Can you explain how to configure it right? 

Thanks in Advance :)

**Comment by aviddot** [comment]
Sorry, for being a dumbass 😅. Commit: https://github.com/aviddot/Pancakeswap-v2-trading-bot/commit/cb02f529317d2a5192bf3bd3c07e57c0f21f2037

I forgot to delete this line, which at the time was used for testing purposes...
